//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Client.AcceptSvr {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcceptReceivingVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.accept")]
    [System.SerializableAttribute()]
    public partial class AcceptReceivingVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryManField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IsNoticeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticeDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PiecesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReceivingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceivingPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StorageLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryCompany {
            get {
                return this.DeliveryCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryCompanyField, value) != true)) {
                    this.DeliveryCompanyField = value;
                    this.RaisePropertyChanged("DeliveryCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryMan {
            get {
                return this.DeliveryManField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryManField, value) != true)) {
                    this.DeliveryManField = value;
                    this.RaisePropertyChanged("DeliveryMan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryMode {
            get {
                return this.DeliveryModeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryModeField, value) != true)) {
                    this.DeliveryModeField = value;
                    this.RaisePropertyChanged("DeliveryMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IsNotice {
            get {
                return this.IsNoticeField;
            }
            set {
                if ((this.IsNoticeField.Equals(value) != true)) {
                    this.IsNoticeField = value;
                    this.RaisePropertyChanged("IsNotice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Names {
            get {
                return this.NamesField;
            }
            set {
                if ((object.ReferenceEquals(this.NamesField, value) != true)) {
                    this.NamesField = value;
                    this.RaisePropertyChanged("Names");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoticeDesc {
            get {
                return this.NoticeDescField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticeDescField, value) != true)) {
                    this.NoticeDescField = value;
                    this.RaisePropertyChanged("NoticeDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Pieces {
            get {
                return this.PiecesField;
            }
            set {
                if ((this.PiecesField.Equals(value) != true)) {
                    this.PiecesField = value;
                    this.RaisePropertyChanged("Pieces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReceivingDate {
            get {
                return this.ReceivingDateField;
            }
            set {
                if ((this.ReceivingDateField.Equals(value) != true)) {
                    this.ReceivingDateField = value;
                    this.RaisePropertyChanged("ReceivingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceivingPerson {
            get {
                return this.ReceivingPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceivingPersonField, value) != true)) {
                    this.ReceivingPersonField = value;
                    this.RaisePropertyChanged("ReceivingPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipAddress {
            get {
                return this.ShipAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipAddressField, value) != true)) {
                    this.ShipAddressField = value;
                    this.RaisePropertyChanged("ShipAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shipper {
            get {
                return this.ShipperField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipperField, value) != true)) {
                    this.ShipperField = value;
                    this.RaisePropertyChanged("Shipper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StorageLocation {
            get {
                return this.StorageLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.StorageLocationField, value) != true)) {
                    this.StorageLocationField = value;
                    this.RaisePropertyChanged("StorageLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackingNumber {
            get {
                return this.TrackingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingNumberField, value) != true)) {
                    this.TrackingNumberField = value;
                    this.RaisePropertyChanged("TrackingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AcceptSvr.IAcceptance")]
    public interface IAcceptance {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceptance/getAcceptReceivingList", ReplyAction="http://tempuri.org/IAcceptance/getAcceptReceivingListResponse")]
        WMS.Client.AcceptSvr.AcceptReceivingVO[] getAcceptReceivingList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceptance/getAcceptReceivingList", ReplyAction="http://tempuri.org/IAcceptance/getAcceptReceivingListResponse")]
        System.Threading.Tasks.Task<WMS.Client.AcceptSvr.AcceptReceivingVO[]> getAcceptReceivingListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceptance/saveAcceptReceiving", ReplyAction="http://tempuri.org/IAcceptance/saveAcceptReceivingResponse")]
        bool saveAcceptReceiving(WMS.Client.AcceptSvr.AcceptReceivingVO pReceivingVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceptance/saveAcceptReceiving", ReplyAction="http://tempuri.org/IAcceptance/saveAcceptReceivingResponse")]
        System.Threading.Tasks.Task<bool> saveAcceptReceivingAsync(WMS.Client.AcceptSvr.AcceptReceivingVO pReceivingVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceptance/enableAndDisableReceivingByReceiveID", ReplyAction="http://tempuri.org/IAcceptance/enableAndDisableReceivingByReceiveIDResponse")]
        bool enableAndDisableReceivingByReceiveID(int pReceiveID, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcceptance/enableAndDisableReceivingByReceiveID", ReplyAction="http://tempuri.org/IAcceptance/enableAndDisableReceivingByReceiveIDResponse")]
        System.Threading.Tasks.Task<bool> enableAndDisableReceivingByReceiveIDAsync(int pReceiveID, int pStatus, string pAccount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAcceptanceChannel : WMS.Client.AcceptSvr.IAcceptance, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AcceptanceClient : System.ServiceModel.ClientBase<WMS.Client.AcceptSvr.IAcceptance>, WMS.Client.AcceptSvr.IAcceptance {
        
        public AcceptanceClient() {
        }
        
        public AcceptanceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AcceptanceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcceptanceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcceptanceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WMS.Client.AcceptSvr.AcceptReceivingVO[] getAcceptReceivingList() {
            return base.Channel.getAcceptReceivingList();
        }
        
        public System.Threading.Tasks.Task<WMS.Client.AcceptSvr.AcceptReceivingVO[]> getAcceptReceivingListAsync() {
            return base.Channel.getAcceptReceivingListAsync();
        }
        
        public bool saveAcceptReceiving(WMS.Client.AcceptSvr.AcceptReceivingVO pReceivingVO) {
            return base.Channel.saveAcceptReceiving(pReceivingVO);
        }
        
        public System.Threading.Tasks.Task<bool> saveAcceptReceivingAsync(WMS.Client.AcceptSvr.AcceptReceivingVO pReceivingVO) {
            return base.Channel.saveAcceptReceivingAsync(pReceivingVO);
        }
        
        public bool enableAndDisableReceivingByReceiveID(int pReceiveID, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableReceivingByReceiveID(pReceiveID, pStatus, pAccount);
        }
        
        public System.Threading.Tasks.Task<bool> enableAndDisableReceivingByReceiveIDAsync(int pReceiveID, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableReceivingByReceiveIDAsync(pReceiveID, pStatus, pAccount);
        }
    }
}
