//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Client.BasicSvr {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WarehouseVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.basic")]
    [System.SerializableAttribute()]
    public partial class WarehouseVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WareNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((this.ParentIDField.Equals(value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WareName {
            get {
                return this.WareNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WareNameField, value) != true)) {
                    this.WareNameField = value;
                    this.RaisePropertyChanged("WareName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.basic")]
    [System.SerializableAttribute()]
    public partial class LocationVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarehouseDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WarehouseIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarehouseDesc {
            get {
                return this.WarehouseDescField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseDescField, value) != true)) {
                    this.WarehouseDescField = value;
                    this.RaisePropertyChanged("WarehouseDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WarehouseID {
            get {
                return this.WarehouseIDField;
            }
            set {
                if ((this.WarehouseIDField.Equals(value) != true)) {
                    this.WarehouseIDField = value;
                    this.RaisePropertyChanged("WarehouseID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.basic")]
    [System.SerializableAttribute()]
    public partial class CustomerVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contacts {
            get {
                return this.ContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactsField, value) != true)) {
                    this.ContactsField = value;
                    this.RaisePropertyChanged("Contacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustName {
            get {
                return this.CustNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustNameField, value) != true)) {
                    this.CustNameField = value;
                    this.RaisePropertyChanged("CustName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.basic")]
    [System.SerializableAttribute()]
    public partial class SupplierVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contacts {
            get {
                return this.ContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactsField, value) != true)) {
                    this.ContactsField = value;
                    this.RaisePropertyChanged("Contacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemCategoryVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.basic")]
    [System.SerializableAttribute()]
    public partial class ItemCategoryVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCategoryName {
            get {
                return this.ItemCategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCategoryNameField, value) != true)) {
                    this.ItemCategoryNameField = value;
                    this.RaisePropertyChanged("ItemCategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((this.ParentIDField.Equals(value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaterialVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.basic")]
    [System.SerializableAttribute()]
    public partial class MaterialVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SupplierIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryDesc {
            get {
                return this.CategoryDescField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryDescField, value) != true)) {
                    this.CategoryDescField = value;
                    this.RaisePropertyChanged("CategoryDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierDesc {
            get {
                return this.SupplierDescField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierDescField, value) != true)) {
                    this.SupplierDescField = value;
                    this.RaisePropertyChanged("SupplierDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SupplierID {
            get {
                return this.SupplierIDField;
            }
            set {
                if ((this.SupplierIDField.Equals(value) != true)) {
                    this.SupplierIDField = value;
                    this.RaisePropertyChanged("SupplierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerialNumberVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.basic")]
    [System.SerializableAttribute()]
    public partial class SerialNumberVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SeqLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SeqStepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuffixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YYMMDDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyDesc {
            get {
                return this.CompanyDescField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyDescField, value) != true)) {
                    this.CompanyDescField = value;
                    this.RaisePropertyChanged("CompanyDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefix {
            get {
                return this.PrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefixField, value) != true)) {
                    this.PrefixField = value;
                    this.RaisePropertyChanged("Prefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SeqLength {
            get {
                return this.SeqLengthField;
            }
            set {
                if ((this.SeqLengthField.Equals(value) != true)) {
                    this.SeqLengthField = value;
                    this.RaisePropertyChanged("SeqLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SeqStep {
            get {
                return this.SeqStepField;
            }
            set {
                if ((this.SeqStepField.Equals(value) != true)) {
                    this.SeqStepField = value;
                    this.RaisePropertyChanged("SeqStep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suffix {
            get {
                return this.SuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.SuffixField, value) != true)) {
                    this.SuffixField = value;
                    this.RaisePropertyChanged("Suffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YYMMDD {
            get {
                return this.YYMMDDField;
            }
            set {
                if ((object.ReferenceEquals(this.YYMMDDField, value) != true)) {
                    this.YYMMDDField = value;
                    this.RaisePropertyChanged("YYMMDD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BasicSvr.IBasic")]
    public interface IBasic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getWarehouseList", ReplyAction="http://tempuri.org/IBasic/getWarehouseListResponse")]
        System.Collections.Generic.List<WMS.Client.BasicSvr.WarehouseVO> getWarehouseList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getWarehouseList", ReplyAction="http://tempuri.org/IBasic/getWarehouseListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.WarehouseVO>> getWarehouseListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getLocationList", ReplyAction="http://tempuri.org/IBasic/getLocationListResponse")]
        System.Collections.Generic.List<WMS.Client.BasicSvr.LocationVO> getLocationList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getLocationList", ReplyAction="http://tempuri.org/IBasic/getLocationListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.LocationVO>> getLocationListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getCustomerList", ReplyAction="http://tempuri.org/IBasic/getCustomerListResponse")]
        System.Collections.Generic.List<WMS.Client.BasicSvr.CustomerVO> getCustomerList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getCustomerList", ReplyAction="http://tempuri.org/IBasic/getCustomerListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.CustomerVO>> getCustomerListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getSupplierList", ReplyAction="http://tempuri.org/IBasic/getSupplierListResponse")]
        System.Collections.Generic.List<WMS.Client.BasicSvr.SupplierVO> getSupplierList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getSupplierList", ReplyAction="http://tempuri.org/IBasic/getSupplierListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.SupplierVO>> getSupplierListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getItemCategoryList", ReplyAction="http://tempuri.org/IBasic/getItemCategoryListResponse")]
        System.Collections.Generic.List<WMS.Client.BasicSvr.ItemCategoryVO> getItemCategoryList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getItemCategoryList", ReplyAction="http://tempuri.org/IBasic/getItemCategoryListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.ItemCategoryVO>> getItemCategoryListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getMaterialList", ReplyAction="http://tempuri.org/IBasic/getMaterialListResponse")]
        System.Collections.Generic.List<WMS.Client.BasicSvr.MaterialVO> getMaterialList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getMaterialList", ReplyAction="http://tempuri.org/IBasic/getMaterialListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.MaterialVO>> getMaterialListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/saveWarehouse", ReplyAction="http://tempuri.org/IBasic/saveWarehouseResponse")]
        bool saveWarehouse(WMS.Client.BasicSvr.WarehouseVO pWarehouseVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/saveWarehouse", ReplyAction="http://tempuri.org/IBasic/saveWarehouseResponse")]
        System.Threading.Tasks.Task<bool> saveWarehouseAsync(WMS.Client.BasicSvr.WarehouseVO pWarehouseVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/saveLocation", ReplyAction="http://tempuri.org/IBasic/saveLocationResponse")]
        bool saveLocation(WMS.Client.BasicSvr.LocationVO pLocationVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/saveLocation", ReplyAction="http://tempuri.org/IBasic/saveLocationResponse")]
        System.Threading.Tasks.Task<bool> saveLocationAsync(WMS.Client.BasicSvr.LocationVO pLocationVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/saveCustomer", ReplyAction="http://tempuri.org/IBasic/saveCustomerResponse")]
        bool saveCustomer(WMS.Client.BasicSvr.CustomerVO pCustomerVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/saveCustomer", ReplyAction="http://tempuri.org/IBasic/saveCustomerResponse")]
        System.Threading.Tasks.Task<bool> saveCustomerAsync(WMS.Client.BasicSvr.CustomerVO pCustomerVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/saveSupplier", ReplyAction="http://tempuri.org/IBasic/saveSupplierResponse")]
        bool saveSupplier(WMS.Client.BasicSvr.SupplierVO pSupplierVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/saveSupplier", ReplyAction="http://tempuri.org/IBasic/saveSupplierResponse")]
        System.Threading.Tasks.Task<bool> saveSupplierAsync(WMS.Client.BasicSvr.SupplierVO pSupplierVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/saveItemCategory", ReplyAction="http://tempuri.org/IBasic/saveItemCategoryResponse")]
        bool saveItemCategory(WMS.Client.BasicSvr.ItemCategoryVO pItemCategoryVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/saveItemCategory", ReplyAction="http://tempuri.org/IBasic/saveItemCategoryResponse")]
        System.Threading.Tasks.Task<bool> saveItemCategoryAsync(WMS.Client.BasicSvr.ItemCategoryVO pItemCategoryVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/saveMaterial", ReplyAction="http://tempuri.org/IBasic/saveMaterialResponse")]
        bool saveMaterial(WMS.Client.BasicSvr.MaterialVO pMaterialVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/saveMaterial", ReplyAction="http://tempuri.org/IBasic/saveMaterialResponse")]
        System.Threading.Tasks.Task<bool> saveMaterialAsync(WMS.Client.BasicSvr.MaterialVO pMaterialVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/enableAndDisableWarehouseByWareID", ReplyAction="http://tempuri.org/IBasic/enableAndDisableWarehouseByWareIDResponse")]
        bool enableAndDisableWarehouseByWareID(int pWarehouseID, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/enableAndDisableWarehouseByWareID", ReplyAction="http://tempuri.org/IBasic/enableAndDisableWarehouseByWareIDResponse")]
        System.Threading.Tasks.Task<bool> enableAndDisableWarehouseByWareIDAsync(int pWarehouseID, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/enableAndDisableLocationByLocationID", ReplyAction="http://tempuri.org/IBasic/enableAndDisableLocationByLocationIDResponse")]
        bool enableAndDisableLocationByLocationID(int pLocationID, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/enableAndDisableLocationByLocationID", ReplyAction="http://tempuri.org/IBasic/enableAndDisableLocationByLocationIDResponse")]
        System.Threading.Tasks.Task<bool> enableAndDisableLocationByLocationIDAsync(int pLocationID, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/enableAndDisableCustomerByCustomerID", ReplyAction="http://tempuri.org/IBasic/enableAndDisableCustomerByCustomerIDResponse")]
        bool enableAndDisableCustomerByCustomerID(int pCustomerID, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/enableAndDisableCustomerByCustomerID", ReplyAction="http://tempuri.org/IBasic/enableAndDisableCustomerByCustomerIDResponse")]
        System.Threading.Tasks.Task<bool> enableAndDisableCustomerByCustomerIDAsync(int pCustomerID, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/enableAndDisableSupplierBySupplierID", ReplyAction="http://tempuri.org/IBasic/enableAndDisableSupplierBySupplierIDResponse")]
        bool enableAndDisableSupplierBySupplierID(int pSupplierID, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/enableAndDisableSupplierBySupplierID", ReplyAction="http://tempuri.org/IBasic/enableAndDisableSupplierBySupplierIDResponse")]
        System.Threading.Tasks.Task<bool> enableAndDisableSupplierBySupplierIDAsync(int pSupplierID, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/enableAndDisableItemCategoryByItemCategoryID", ReplyAction="http://tempuri.org/IBasic/enableAndDisableItemCategoryByItemCategoryIDResponse")]
        bool enableAndDisableItemCategoryByItemCategoryID(int pItemCategoryID, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/enableAndDisableItemCategoryByItemCategoryID", ReplyAction="http://tempuri.org/IBasic/enableAndDisableItemCategoryByItemCategoryIDResponse")]
        System.Threading.Tasks.Task<bool> enableAndDisableItemCategoryByItemCategoryIDAsync(int pItemCategoryID, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/enableAndDisableMaterialByMaterialID", ReplyAction="http://tempuri.org/IBasic/enableAndDisableMaterialByMaterialIDResponse")]
        bool enableAndDisableMaterialByMaterialID(int pMaterialID, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/enableAndDisableMaterialByMaterialID", ReplyAction="http://tempuri.org/IBasic/enableAndDisableMaterialByMaterialIDResponse")]
        System.Threading.Tasks.Task<bool> enableAndDisableMaterialByMaterialIDAsync(int pMaterialID, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getLocationByWarehouseID", ReplyAction="http://tempuri.org/IBasic/getLocationByWarehouseIDResponse")]
        System.Collections.Generic.List<WMS.Client.BasicSvr.LocationVO> getLocationByWarehouseID(int pWarehouseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getLocationByWarehouseID", ReplyAction="http://tempuri.org/IBasic/getLocationByWarehouseIDResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.LocationVO>> getLocationByWarehouseIDAsync(int pWarehouseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getMaterialByCategoryID", ReplyAction="http://tempuri.org/IBasic/getMaterialByCategoryIDResponse")]
        System.Collections.Generic.List<WMS.Client.BasicSvr.MaterialVO> getMaterialByCategoryID(int pCategoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getMaterialByCategoryID", ReplyAction="http://tempuri.org/IBasic/getMaterialByCategoryIDResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.MaterialVO>> getMaterialByCategoryIDAsync(int pCategoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getSerialNumberList", ReplyAction="http://tempuri.org/IBasic/getSerialNumberListResponse")]
        System.Collections.Generic.List<WMS.Client.BasicSvr.SerialNumberVO> getSerialNumberList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getSerialNumberList", ReplyAction="http://tempuri.org/IBasic/getSerialNumberListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.SerialNumberVO>> getSerialNumberListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/saveSerialNumber", ReplyAction="http://tempuri.org/IBasic/saveSerialNumberResponse")]
        bool saveSerialNumber(WMS.Client.BasicSvr.SerialNumberVO pSNVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/saveSerialNumber", ReplyAction="http://tempuri.org/IBasic/saveSerialNumberResponse")]
        System.Threading.Tasks.Task<bool> saveSerialNumberAsync(WMS.Client.BasicSvr.SerialNumberVO pSNVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/enableAndDisableSerialNumberBySerialID", ReplyAction="http://tempuri.org/IBasic/enableAndDisableSerialNumberBySerialIDResponse")]
        bool enableAndDisableSerialNumberBySerialID(int pSerialID, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/enableAndDisableSerialNumberBySerialID", ReplyAction="http://tempuri.org/IBasic/enableAndDisableSerialNumberBySerialIDResponse")]
        System.Threading.Tasks.Task<bool> enableAndDisableSerialNumberBySerialIDAsync(int pSerialID, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getSN", ReplyAction="http://tempuri.org/IBasic/getSNResponse")]
        string getSN(string pType, int pCompanyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasic/getSN", ReplyAction="http://tempuri.org/IBasic/getSNResponse")]
        System.Threading.Tasks.Task<string> getSNAsync(string pType, int pCompanyID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBasicChannel : WMS.Client.BasicSvr.IBasic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BasicClient : System.ServiceModel.ClientBase<WMS.Client.BasicSvr.IBasic>, WMS.Client.BasicSvr.IBasic {
        
        public BasicClient() {
        }
        
        public BasicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BasicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WMS.Client.BasicSvr.WarehouseVO> getWarehouseList() {
            return base.Channel.getWarehouseList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.WarehouseVO>> getWarehouseListAsync() {
            return base.Channel.getWarehouseListAsync();
        }
        
        public System.Collections.Generic.List<WMS.Client.BasicSvr.LocationVO> getLocationList() {
            return base.Channel.getLocationList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.LocationVO>> getLocationListAsync() {
            return base.Channel.getLocationListAsync();
        }
        
        public System.Collections.Generic.List<WMS.Client.BasicSvr.CustomerVO> getCustomerList() {
            return base.Channel.getCustomerList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.CustomerVO>> getCustomerListAsync() {
            return base.Channel.getCustomerListAsync();
        }
        
        public System.Collections.Generic.List<WMS.Client.BasicSvr.SupplierVO> getSupplierList() {
            return base.Channel.getSupplierList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.SupplierVO>> getSupplierListAsync() {
            return base.Channel.getSupplierListAsync();
        }
        
        public System.Collections.Generic.List<WMS.Client.BasicSvr.ItemCategoryVO> getItemCategoryList() {
            return base.Channel.getItemCategoryList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.ItemCategoryVO>> getItemCategoryListAsync() {
            return base.Channel.getItemCategoryListAsync();
        }
        
        public System.Collections.Generic.List<WMS.Client.BasicSvr.MaterialVO> getMaterialList() {
            return base.Channel.getMaterialList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.MaterialVO>> getMaterialListAsync() {
            return base.Channel.getMaterialListAsync();
        }
        
        public bool saveWarehouse(WMS.Client.BasicSvr.WarehouseVO pWarehouseVO) {
            return base.Channel.saveWarehouse(pWarehouseVO);
        }
        
        public System.Threading.Tasks.Task<bool> saveWarehouseAsync(WMS.Client.BasicSvr.WarehouseVO pWarehouseVO) {
            return base.Channel.saveWarehouseAsync(pWarehouseVO);
        }
        
        public bool saveLocation(WMS.Client.BasicSvr.LocationVO pLocationVO) {
            return base.Channel.saveLocation(pLocationVO);
        }
        
        public System.Threading.Tasks.Task<bool> saveLocationAsync(WMS.Client.BasicSvr.LocationVO pLocationVO) {
            return base.Channel.saveLocationAsync(pLocationVO);
        }
        
        public bool saveCustomer(WMS.Client.BasicSvr.CustomerVO pCustomerVO) {
            return base.Channel.saveCustomer(pCustomerVO);
        }
        
        public System.Threading.Tasks.Task<bool> saveCustomerAsync(WMS.Client.BasicSvr.CustomerVO pCustomerVO) {
            return base.Channel.saveCustomerAsync(pCustomerVO);
        }
        
        public bool saveSupplier(WMS.Client.BasicSvr.SupplierVO pSupplierVO) {
            return base.Channel.saveSupplier(pSupplierVO);
        }
        
        public System.Threading.Tasks.Task<bool> saveSupplierAsync(WMS.Client.BasicSvr.SupplierVO pSupplierVO) {
            return base.Channel.saveSupplierAsync(pSupplierVO);
        }
        
        public bool saveItemCategory(WMS.Client.BasicSvr.ItemCategoryVO pItemCategoryVO) {
            return base.Channel.saveItemCategory(pItemCategoryVO);
        }
        
        public System.Threading.Tasks.Task<bool> saveItemCategoryAsync(WMS.Client.BasicSvr.ItemCategoryVO pItemCategoryVO) {
            return base.Channel.saveItemCategoryAsync(pItemCategoryVO);
        }
        
        public bool saveMaterial(WMS.Client.BasicSvr.MaterialVO pMaterialVO) {
            return base.Channel.saveMaterial(pMaterialVO);
        }
        
        public System.Threading.Tasks.Task<bool> saveMaterialAsync(WMS.Client.BasicSvr.MaterialVO pMaterialVO) {
            return base.Channel.saveMaterialAsync(pMaterialVO);
        }
        
        public bool enableAndDisableWarehouseByWareID(int pWarehouseID, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableWarehouseByWareID(pWarehouseID, pStatus, pAccount);
        }
        
        public System.Threading.Tasks.Task<bool> enableAndDisableWarehouseByWareIDAsync(int pWarehouseID, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableWarehouseByWareIDAsync(pWarehouseID, pStatus, pAccount);
        }
        
        public bool enableAndDisableLocationByLocationID(int pLocationID, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableLocationByLocationID(pLocationID, pStatus, pAccount);
        }
        
        public System.Threading.Tasks.Task<bool> enableAndDisableLocationByLocationIDAsync(int pLocationID, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableLocationByLocationIDAsync(pLocationID, pStatus, pAccount);
        }
        
        public bool enableAndDisableCustomerByCustomerID(int pCustomerID, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableCustomerByCustomerID(pCustomerID, pStatus, pAccount);
        }
        
        public System.Threading.Tasks.Task<bool> enableAndDisableCustomerByCustomerIDAsync(int pCustomerID, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableCustomerByCustomerIDAsync(pCustomerID, pStatus, pAccount);
        }
        
        public bool enableAndDisableSupplierBySupplierID(int pSupplierID, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableSupplierBySupplierID(pSupplierID, pStatus, pAccount);
        }
        
        public System.Threading.Tasks.Task<bool> enableAndDisableSupplierBySupplierIDAsync(int pSupplierID, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableSupplierBySupplierIDAsync(pSupplierID, pStatus, pAccount);
        }
        
        public bool enableAndDisableItemCategoryByItemCategoryID(int pItemCategoryID, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableItemCategoryByItemCategoryID(pItemCategoryID, pStatus, pAccount);
        }
        
        public System.Threading.Tasks.Task<bool> enableAndDisableItemCategoryByItemCategoryIDAsync(int pItemCategoryID, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableItemCategoryByItemCategoryIDAsync(pItemCategoryID, pStatus, pAccount);
        }
        
        public bool enableAndDisableMaterialByMaterialID(int pMaterialID, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableMaterialByMaterialID(pMaterialID, pStatus, pAccount);
        }
        
        public System.Threading.Tasks.Task<bool> enableAndDisableMaterialByMaterialIDAsync(int pMaterialID, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableMaterialByMaterialIDAsync(pMaterialID, pStatus, pAccount);
        }
        
        public System.Collections.Generic.List<WMS.Client.BasicSvr.LocationVO> getLocationByWarehouseID(int pWarehouseID) {
            return base.Channel.getLocationByWarehouseID(pWarehouseID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.LocationVO>> getLocationByWarehouseIDAsync(int pWarehouseID) {
            return base.Channel.getLocationByWarehouseIDAsync(pWarehouseID);
        }
        
        public System.Collections.Generic.List<WMS.Client.BasicSvr.MaterialVO> getMaterialByCategoryID(int pCategoryID) {
            return base.Channel.getMaterialByCategoryID(pCategoryID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.MaterialVO>> getMaterialByCategoryIDAsync(int pCategoryID) {
            return base.Channel.getMaterialByCategoryIDAsync(pCategoryID);
        }
        
        public System.Collections.Generic.List<WMS.Client.BasicSvr.SerialNumberVO> getSerialNumberList() {
            return base.Channel.getSerialNumberList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WMS.Client.BasicSvr.SerialNumberVO>> getSerialNumberListAsync() {
            return base.Channel.getSerialNumberListAsync();
        }
        
        public bool saveSerialNumber(WMS.Client.BasicSvr.SerialNumberVO pSNVO) {
            return base.Channel.saveSerialNumber(pSNVO);
        }
        
        public System.Threading.Tasks.Task<bool> saveSerialNumberAsync(WMS.Client.BasicSvr.SerialNumberVO pSNVO) {
            return base.Channel.saveSerialNumberAsync(pSNVO);
        }
        
        public bool enableAndDisableSerialNumberBySerialID(int pSerialID, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableSerialNumberBySerialID(pSerialID, pStatus, pAccount);
        }
        
        public System.Threading.Tasks.Task<bool> enableAndDisableSerialNumberBySerialIDAsync(int pSerialID, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableSerialNumberBySerialIDAsync(pSerialID, pStatus, pAccount);
        }
        
        public string getSN(string pType, int pCompanyID) {
            return base.Channel.getSN(pType, pCompanyID);
        }
        
        public System.Threading.Tasks.Task<string> getSNAsync(string pType, int pCompanyID) {
            return base.Channel.getSNAsync(pType, pCompanyID);
        }
    }
}
