//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Client.SysInfoSvr {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysCompanyEasyVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.sys")]
    [System.SerializableAttribute()]
    public partial class SysCompanyEasyVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysAccountEasyVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.sys")]
    [System.SerializableAttribute()]
    public partial class SysAccountEasyVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysRoleEasyVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.sys")]
    [System.SerializableAttribute()]
    public partial class SysRoleEasyVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysMenuVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.sys")]
    [System.SerializableAttribute()]
    public partial class SysMenuVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CmdExeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CmdFormField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CmdExe {
            get {
                return this.CmdExeField;
            }
            set {
                if ((object.ReferenceEquals(this.CmdExeField, value) != true)) {
                    this.CmdExeField = value;
                    this.RaisePropertyChanged("CmdExe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CmdForm {
            get {
                return this.CmdFormField;
            }
            set {
                if ((object.ReferenceEquals(this.CmdFormField, value) != true)) {
                    this.CmdFormField = value;
                    this.RaisePropertyChanged("CmdForm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Icon {
            get {
                return this.IconField;
            }
            set {
                if ((object.ReferenceEquals(this.IconField, value) != true)) {
                    this.IconField = value;
                    this.RaisePropertyChanged("Icon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuName {
            get {
                return this.MenuNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuNameField, value) != true)) {
                    this.MenuNameField = value;
                    this.RaisePropertyChanged("MenuName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((this.ParentIDField.Equals(value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysRoleVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.sys")]
    [System.SerializableAttribute()]
    public partial class SysRoleVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysCompanyVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.sys")]
    [System.SerializableAttribute()]
    public partial class SysCompanyVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorporationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contacts {
            get {
                return this.ContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactsField, value) != true)) {
                    this.ContactsField = value;
                    this.RaisePropertyChanged("Contacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Corporation {
            get {
                return this.CorporationField;
            }
            set {
                if ((object.ReferenceEquals(this.CorporationField, value) != true)) {
                    this.CorporationField = value;
                    this.RaisePropertyChanged("Corporation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationNo {
            get {
                return this.RegistrationNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationNoField, value) != true)) {
                    this.RegistrationNoField = value;
                    this.RaisePropertyChanged("RegistrationNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysStructureVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.sys")]
    [System.SerializableAttribute()]
    public partial class SysStructureVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StructureNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((this.ParentIDField.Equals(value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StructureName {
            get {
                return this.StructureNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StructureNameField, value) != true)) {
                    this.StructureNameField = value;
                    this.RaisePropertyChanged("StructureName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysAccountVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.sys")]
    [System.SerializableAttribute()]
    public partial class SysAccountVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EducationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmergencyContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmergencyPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnglishNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> HireDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarriageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StructureDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StructureIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Education {
            get {
                return this.EducationField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationField, value) != true)) {
                    this.EducationField = value;
                    this.RaisePropertyChanged("Education");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmergencyContacts {
            get {
                return this.EmergencyContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.EmergencyContactsField, value) != true)) {
                    this.EmergencyContactsField = value;
                    this.RaisePropertyChanged("EmergencyContacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmergencyPhone {
            get {
                return this.EmergencyPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.EmergencyPhoneField, value) != true)) {
                    this.EmergencyPhoneField = value;
                    this.RaisePropertyChanged("EmergencyPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnglishName {
            get {
                return this.EnglishNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EnglishNameField, value) != true)) {
                    this.EnglishNameField = value;
                    this.RaisePropertyChanged("EnglishName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> HireDate {
            get {
                return this.HireDateField;
            }
            set {
                if ((this.HireDateField.Equals(value) != true)) {
                    this.HireDateField = value;
                    this.RaisePropertyChanged("HireDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marriage {
            get {
                return this.MarriageField;
            }
            set {
                if ((object.ReferenceEquals(this.MarriageField, value) != true)) {
                    this.MarriageField = value;
                    this.RaisePropertyChanged("Marriage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StructureDesc {
            get {
                return this.StructureDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StructureDescField, value) != true)) {
                    this.StructureDescField = value;
                    this.RaisePropertyChanged("StructureDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StructureID {
            get {
                return this.StructureIDField;
            }
            set {
                if ((this.StructureIDField.Equals(value) != true)) {
                    this.StructureIDField = value;
                    this.RaisePropertyChanged("StructureID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysUserDefinedVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.sys")]
    [System.SerializableAttribute()]
    public partial class SysUserDefinedVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SysCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SysCode {
            get {
                return this.SysCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SysCodeField, value) != true)) {
                    this.SysCodeField = value;
                    this.RaisePropertyChanged("SysCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UKey {
            get {
                return this.UKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.UKeyField, value) != true)) {
                    this.UKeyField = value;
                    this.RaisePropertyChanged("UKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UValue {
            get {
                return this.UValueField;
            }
            set {
                if ((object.ReferenceEquals(this.UValueField, value) != true)) {
                    this.UValueField = value;
                    this.RaisePropertyChanged("UValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysRoleAccountVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.sys")]
    [System.SerializableAttribute()]
    public partial class SysRoleAccountVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((this.AccountIDField.Equals(value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysRoleStructureVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.sys")]
    [System.SerializableAttribute()]
    public partial class SysRoleStructureVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StructureIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StructureID {
            get {
                return this.StructureIDField;
            }
            set {
                if ((this.StructureIDField.Equals(value) != true)) {
                    this.StructureIDField = value;
                    this.RaisePropertyChanged("StructureID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysRoleMenuVO", Namespace="http://schemas.datacontract.org/2004/07/WMS.Lib.vo.sys")]
    [System.SerializableAttribute()]
    public partial class SysRoleMenuVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MenuIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MenuID {
            get {
                return this.MenuIDField;
            }
            set {
                if ((this.MenuIDField.Equals(value) != true)) {
                    this.MenuIDField = value;
                    this.RaisePropertyChanged("MenuID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SysInfoSvr.ISysInfo")]
    public interface ISysInfo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/getCompanyEasyList", ReplyAction="http://tempuri.org/ISysInfo/getCompanyEasyListResponse")]
        System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysCompanyEasyVO> getCompanyEasyList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/checkLogin", ReplyAction="http://tempuri.org/ISysInfo/checkLoginResponse")]
        WMS.Client.SysInfoSvr.SysAccountEasyVO checkLogin(string pAccount, string pPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/getRoleByAccount", ReplyAction="http://tempuri.org/ISysInfo/getRoleByAccountResponse")]
        System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysRoleEasyVO> getRoleByAccount(string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/getMenuByRoleId", ReplyAction="http://tempuri.org/ISysInfo/getMenuByRoleIdResponse")]
        System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysMenuVO> getMenuByRoleId(int pRoleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/getMenuList", ReplyAction="http://tempuri.org/ISysInfo/getMenuListResponse")]
        System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysMenuVO> getMenuList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/getRoleList", ReplyAction="http://tempuri.org/ISysInfo/getRoleListResponse")]
        System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysRoleVO> getRoleList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/getCompanyList", ReplyAction="http://tempuri.org/ISysInfo/getCompanyListResponse")]
        System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysCompanyVO> getCompanyList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/getStructureList", ReplyAction="http://tempuri.org/ISysInfo/getStructureListResponse")]
        System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysStructureVO> getStructureList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/getAccountList", ReplyAction="http://tempuri.org/ISysInfo/getAccountListResponse")]
        System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysAccountVO> getAccountList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/getUserDeinedList", ReplyAction="http://tempuri.org/ISysInfo/getUserDeinedListResponse")]
        System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysUserDefinedVO> getUserDeinedList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/saveMenu", ReplyAction="http://tempuri.org/ISysInfo/saveMenuResponse")]
        bool saveMenu(WMS.Client.SysInfoSvr.SysMenuVO pMenuVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/saveRole", ReplyAction="http://tempuri.org/ISysInfo/saveRoleResponse")]
        bool saveRole(WMS.Client.SysInfoSvr.SysRoleVO pRoleVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/saveCompany", ReplyAction="http://tempuri.org/ISysInfo/saveCompanyResponse")]
        bool saveCompany(WMS.Client.SysInfoSvr.SysCompanyVO pCompanyVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/saveStructure", ReplyAction="http://tempuri.org/ISysInfo/saveStructureResponse")]
        bool saveStructure(WMS.Client.SysInfoSvr.SysStructureVO pStructureVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/saveAccount", ReplyAction="http://tempuri.org/ISysInfo/saveAccountResponse")]
        bool saveAccount(WMS.Client.SysInfoSvr.SysAccountVO pAccountVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/saveUserDefined", ReplyAction="http://tempuri.org/ISysInfo/saveUserDefinedResponse")]
        bool saveUserDefined(WMS.Client.SysInfoSvr.SysUserDefinedVO pUserDefinedVO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/changePassword", ReplyAction="http://tempuri.org/ISysInfo/changePasswordResponse")]
        bool changePassword(string pAccount, string pOldPwd, string pNewPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/resetPassword", ReplyAction="http://tempuri.org/ISysInfo/resetPasswordResponse")]
        bool resetPassword(string pAccount, string pPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/enableAndDisableByMenuId", ReplyAction="http://tempuri.org/ISysInfo/enableAndDisableByMenuIdResponse")]
        bool enableAndDisableByMenuId(int pMenuId, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/enableAndDisableByCompanyId", ReplyAction="http://tempuri.org/ISysInfo/enableAndDisableByCompanyIdResponse")]
        bool enableAndDisableByCompanyId(int pCompanyId, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/enableAndDisableByStructureId", ReplyAction="http://tempuri.org/ISysInfo/enableAndDisableByStructureIdResponse")]
        bool enableAndDisableByStructureId(int pStructureId, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/enableAndDisableByAccountId", ReplyAction="http://tempuri.org/ISysInfo/enableAndDisableByAccountIdResponse")]
        bool enableAndDisableByAccountId(int pAccountId, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/enableAndDisableByRoleId", ReplyAction="http://tempuri.org/ISysInfo/enableAndDisableByRoleIdResponse")]
        bool enableAndDisableByRoleId(int pRoleId, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/enableAndDisableByUdcId", ReplyAction="http://tempuri.org/ISysInfo/enableAndDisableByUdcIdResponse")]
        bool enableAndDisableByUdcId(int pUdcId, int pStatus, string pAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/getRoleAccountByAccountId", ReplyAction="http://tempuri.org/ISysInfo/getRoleAccountByAccountIdResponse")]
        System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysRoleAccountVO> getRoleAccountByAccountId(int pAccountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/removeAccountId2Role", ReplyAction="http://tempuri.org/ISysInfo/removeAccountId2RoleResponse")]
        void removeAccountId2Role(int pRoleId, int pAccountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/saveAccountId2Role", ReplyAction="http://tempuri.org/ISysInfo/saveAccountId2RoleResponse")]
        void saveAccountId2Role(int pRoleId, int pAccountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/getRoleStructureByStructureId", ReplyAction="http://tempuri.org/ISysInfo/getRoleStructureByStructureIdResponse")]
        System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysRoleStructureVO> getRoleStructureByStructureId(int pStructureId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/removeStructureId2Role", ReplyAction="http://tempuri.org/ISysInfo/removeStructureId2RoleResponse")]
        void removeStructureId2Role(int pRoleId, int pStructureId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/saveStructureId2Role", ReplyAction="http://tempuri.org/ISysInfo/saveStructureId2RoleResponse")]
        void saveStructureId2Role(int pRoleId, int pStructureId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/getRoleMenuByRoleId", ReplyAction="http://tempuri.org/ISysInfo/getRoleMenuByRoleIdResponse")]
        System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysRoleMenuVO> getRoleMenuByRoleId(int pRoleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/removeMenuId2Role", ReplyAction="http://tempuri.org/ISysInfo/removeMenuId2RoleResponse")]
        void removeMenuId2Role(int pRoleId, int pMenuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysInfo/saveMenuId2Role", ReplyAction="http://tempuri.org/ISysInfo/saveMenuId2RoleResponse")]
        void saveMenuId2Role(int pRoleId, int pMenuId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISysInfoChannel : WMS.Client.SysInfoSvr.ISysInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SysInfoClient : System.ServiceModel.ClientBase<WMS.Client.SysInfoSvr.ISysInfo>, WMS.Client.SysInfoSvr.ISysInfo {
        
        public SysInfoClient() {
        }
        
        public SysInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SysInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SysInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SysInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysCompanyEasyVO> getCompanyEasyList() {
            return base.Channel.getCompanyEasyList();
        }
        
        public WMS.Client.SysInfoSvr.SysAccountEasyVO checkLogin(string pAccount, string pPwd) {
            return base.Channel.checkLogin(pAccount, pPwd);
        }
        
        public System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysRoleEasyVO> getRoleByAccount(string pAccount) {
            return base.Channel.getRoleByAccount(pAccount);
        }
        
        public System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysMenuVO> getMenuByRoleId(int pRoleId) {
            return base.Channel.getMenuByRoleId(pRoleId);
        }
        
        public System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysMenuVO> getMenuList() {
            return base.Channel.getMenuList();
        }
        
        public System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysRoleVO> getRoleList() {
            return base.Channel.getRoleList();
        }
        
        public System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysCompanyVO> getCompanyList() {
            return base.Channel.getCompanyList();
        }
        
        public System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysStructureVO> getStructureList() {
            return base.Channel.getStructureList();
        }
        
        public System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysAccountVO> getAccountList() {
            return base.Channel.getAccountList();
        }
        
        public System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysUserDefinedVO> getUserDeinedList() {
            return base.Channel.getUserDeinedList();
        }
        
        public bool saveMenu(WMS.Client.SysInfoSvr.SysMenuVO pMenuVO) {
            return base.Channel.saveMenu(pMenuVO);
        }
        
        public bool saveRole(WMS.Client.SysInfoSvr.SysRoleVO pRoleVO) {
            return base.Channel.saveRole(pRoleVO);
        }
        
        public bool saveCompany(WMS.Client.SysInfoSvr.SysCompanyVO pCompanyVO) {
            return base.Channel.saveCompany(pCompanyVO);
        }
        
        public bool saveStructure(WMS.Client.SysInfoSvr.SysStructureVO pStructureVO) {
            return base.Channel.saveStructure(pStructureVO);
        }
        
        public bool saveAccount(WMS.Client.SysInfoSvr.SysAccountVO pAccountVO) {
            return base.Channel.saveAccount(pAccountVO);
        }
        
        public bool saveUserDefined(WMS.Client.SysInfoSvr.SysUserDefinedVO pUserDefinedVO) {
            return base.Channel.saveUserDefined(pUserDefinedVO);
        }
        
        public bool changePassword(string pAccount, string pOldPwd, string pNewPwd) {
            return base.Channel.changePassword(pAccount, pOldPwd, pNewPwd);
        }
        
        public bool resetPassword(string pAccount, string pPwd) {
            return base.Channel.resetPassword(pAccount, pPwd);
        }
        
        public bool enableAndDisableByMenuId(int pMenuId, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableByMenuId(pMenuId, pStatus, pAccount);
        }
        
        public bool enableAndDisableByCompanyId(int pCompanyId, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableByCompanyId(pCompanyId, pStatus, pAccount);
        }
        
        public bool enableAndDisableByStructureId(int pStructureId, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableByStructureId(pStructureId, pStatus, pAccount);
        }
        
        public bool enableAndDisableByAccountId(int pAccountId, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableByAccountId(pAccountId, pStatus, pAccount);
        }
        
        public bool enableAndDisableByRoleId(int pRoleId, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableByRoleId(pRoleId, pStatus, pAccount);
        }
        
        public bool enableAndDisableByUdcId(int pUdcId, int pStatus, string pAccount) {
            return base.Channel.enableAndDisableByUdcId(pUdcId, pStatus, pAccount);
        }
        
        public System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysRoleAccountVO> getRoleAccountByAccountId(int pAccountId) {
            return base.Channel.getRoleAccountByAccountId(pAccountId);
        }
        
        public void removeAccountId2Role(int pRoleId, int pAccountId) {
            base.Channel.removeAccountId2Role(pRoleId, pAccountId);
        }
        
        public void saveAccountId2Role(int pRoleId, int pAccountId) {
            base.Channel.saveAccountId2Role(pRoleId, pAccountId);
        }
        
        public System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysRoleStructureVO> getRoleStructureByStructureId(int pStructureId) {
            return base.Channel.getRoleStructureByStructureId(pStructureId);
        }
        
        public void removeStructureId2Role(int pRoleId, int pStructureId) {
            base.Channel.removeStructureId2Role(pRoleId, pStructureId);
        }
        
        public void saveStructureId2Role(int pRoleId, int pStructureId) {
            base.Channel.saveStructureId2Role(pRoleId, pStructureId);
        }
        
        public System.Collections.Generic.List<WMS.Client.SysInfoSvr.SysRoleMenuVO> getRoleMenuByRoleId(int pRoleId) {
            return base.Channel.getRoleMenuByRoleId(pRoleId);
        }
        
        public void removeMenuId2Role(int pRoleId, int pMenuId) {
            base.Channel.removeMenuId2Role(pRoleId, pMenuId);
        }
        
        public void saveMenuId2Role(int pRoleId, int pMenuId) {
            base.Channel.saveMenuId2Role(pRoleId, pMenuId);
        }
    }
}
