#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO.Lib
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Archer.CS.System")]
	public partial class CS_SystemDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertTB_Account(TB_Account instance);
    partial void UpdateTB_Account(TB_Account instance);
    partial void DeleteTB_Account(TB_Account instance);
    partial void InsertTB_Department(TB_Department instance);
    partial void UpdateTB_Department(TB_Department instance);
    partial void DeleteTB_Department(TB_Department instance);
    partial void InsertTB_Factory(TB_Factory instance);
    partial void UpdateTB_Factory(TB_Factory instance);
    partial void DeleteTB_Factory(TB_Factory instance);
    partial void InsertTB_Menu(TB_Menu instance);
    partial void UpdateTB_Menu(TB_Menu instance);
    partial void DeleteTB_Menu(TB_Menu instance);
    partial void InsertTB_Role(TB_Role instance);
    partial void UpdateTB_Role(TB_Role instance);
    partial void DeleteTB_Role(TB_Role instance);
    partial void InsertTB_Role_R(TB_Role_R instance);
    partial void UpdateTB_Role_R(TB_Role_R instance);
    partial void DeleteTB_Role_R(TB_Role_R instance);
    partial void InsertTB_Udc(TB_Udc instance);
    partial void UpdateTB_Udc(TB_Udc instance);
    partial void DeleteTB_Udc(TB_Udc instance);
    #endregion
		
		public CS_SystemDataContext() : 
				base(global::SSO.Lib.Properties.Settings.Default.Archer_CS_SystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CS_SystemDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CS_SystemDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CS_SystemDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CS_SystemDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TB_Account> TB_Account
		{
			get
			{
				return this.GetTable<TB_Account>();
			}
		}
		
		public System.Data.Linq.Table<TB_Department> TB_Department
		{
			get
			{
				return this.GetTable<TB_Department>();
			}
		}
		
		public System.Data.Linq.Table<TB_Factory> TB_Factory
		{
			get
			{
				return this.GetTable<TB_Factory>();
			}
		}
		
		public System.Data.Linq.Table<TB_Menu> TB_Menu
		{
			get
			{
				return this.GetTable<TB_Menu>();
			}
		}
		
		public System.Data.Linq.Table<TB_Role> TB_Role
		{
			get
			{
				return this.GetTable<TB_Role>();
			}
		}
		
		public System.Data.Linq.Table<TB_Role_R> TB_Role_R
		{
			get
			{
				return this.GetTable<TB_Role_R>();
			}
		}
		
		public System.Data.Linq.Table<TB_Udc> TB_Udc
		{
			get
			{
				return this.GetTable<TB_Udc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Account")]
	public partial class TB_Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _Code;
		
		private string _Password;
		
		private string _Name;
		
		private string _EngName;
		
		private System.Nullable<System.Guid> _DeptID;
		
		private string _DeptCode;
		
		private string _Email;
		
		private string _Tel;
		
		private string _Status;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _CreateOn;
		
		private string _UpdateBy;
		
		private System.Nullable<System.DateTime> _UpdateOn;
		
		private string _Segment1;
		
		private string _Segment2;
		
		private string _Segment3;
		
		private string _Segment4;
		
		private string _Segment5;
		
		private string _Segment6;
		
		private string _Segment7;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEngNameChanging(string value);
    partial void OnEngNameChanged();
    partial void OnDeptIDChanging(System.Nullable<System.Guid> value);
    partial void OnDeptIDChanged();
    partial void OnDeptCodeChanging(string value);
    partial void OnDeptCodeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnCreateOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateOnChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    partial void OnUpdateOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateOnChanged();
    partial void OnSegment1Changing(string value);
    partial void OnSegment1Changed();
    partial void OnSegment2Changing(string value);
    partial void OnSegment2Changed();
    partial void OnSegment3Changing(string value);
    partial void OnSegment3Changed();
    partial void OnSegment4Changing(string value);
    partial void OnSegment4Changed();
    partial void OnSegment5Changing(string value);
    partial void OnSegment5Changed();
    partial void OnSegment6Changing(string value);
    partial void OnSegment6Changed();
    partial void OnSegment7Changing(string value);
    partial void OnSegment7Changed();
    #endregion
		
		public TB_Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngName", DbType="NVarChar(50)")]
		public string EngName
		{
			get
			{
				return this._EngName;
			}
			set
			{
				if ((this._EngName != value))
				{
					this.OnEngNameChanging(value);
					this.SendPropertyChanging();
					this._EngName = value;
					this.SendPropertyChanged("EngName");
					this.OnEngNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> DeptID
		{
			get
			{
				return this._DeptID;
			}
			set
			{
				if ((this._DeptID != value))
				{
					this.OnDeptIDChanging(value);
					this.SendPropertyChanging();
					this._DeptID = value;
					this.SendPropertyChanged("DeptID");
					this.OnDeptIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptCode", DbType="NVarChar(50)")]
		public string DeptCode
		{
			get
			{
				return this._DeptCode;
			}
			set
			{
				if ((this._DeptCode != value))
				{
					this.OnDeptCodeChanging(value);
					this.SendPropertyChanging();
					this._DeptCode = value;
					this.SendPropertyChanged("DeptCode");
					this.OnDeptCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(10)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateOn
		{
			get
			{
				return this._CreateOn;
			}
			set
			{
				if ((this._CreateOn != value))
				{
					this.OnCreateOnChanging(value);
					this.SendPropertyChanging();
					this._CreateOn = value;
					this.SendPropertyChanged("CreateOn");
					this.OnCreateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(50)")]
		public string UpdateBy
		{
			get
			{
				return this._UpdateBy;
			}
			set
			{
				if ((this._UpdateBy != value))
				{
					this.OnUpdateByChanging(value);
					this.SendPropertyChanging();
					this._UpdateBy = value;
					this.SendPropertyChanged("UpdateBy");
					this.OnUpdateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateOn
		{
			get
			{
				return this._UpdateOn;
			}
			set
			{
				if ((this._UpdateOn != value))
				{
					this.OnUpdateOnChanging(value);
					this.SendPropertyChanging();
					this._UpdateOn = value;
					this.SendPropertyChanged("UpdateOn");
					this.OnUpdateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment1", DbType="NVarChar(255)")]
		public string Segment1
		{
			get
			{
				return this._Segment1;
			}
			set
			{
				if ((this._Segment1 != value))
				{
					this.OnSegment1Changing(value);
					this.SendPropertyChanging();
					this._Segment1 = value;
					this.SendPropertyChanged("Segment1");
					this.OnSegment1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment2", DbType="NVarChar(255)")]
		public string Segment2
		{
			get
			{
				return this._Segment2;
			}
			set
			{
				if ((this._Segment2 != value))
				{
					this.OnSegment2Changing(value);
					this.SendPropertyChanging();
					this._Segment2 = value;
					this.SendPropertyChanged("Segment2");
					this.OnSegment2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment3", DbType="NVarChar(255)")]
		public string Segment3
		{
			get
			{
				return this._Segment3;
			}
			set
			{
				if ((this._Segment3 != value))
				{
					this.OnSegment3Changing(value);
					this.SendPropertyChanging();
					this._Segment3 = value;
					this.SendPropertyChanged("Segment3");
					this.OnSegment3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment4", DbType="NVarChar(255)")]
		public string Segment4
		{
			get
			{
				return this._Segment4;
			}
			set
			{
				if ((this._Segment4 != value))
				{
					this.OnSegment4Changing(value);
					this.SendPropertyChanging();
					this._Segment4 = value;
					this.SendPropertyChanged("Segment4");
					this.OnSegment4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment5", DbType="NVarChar(255)")]
		public string Segment5
		{
			get
			{
				return this._Segment5;
			}
			set
			{
				if ((this._Segment5 != value))
				{
					this.OnSegment5Changing(value);
					this.SendPropertyChanging();
					this._Segment5 = value;
					this.SendPropertyChanged("Segment5");
					this.OnSegment5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment6", DbType="NVarChar(255)")]
		public string Segment6
		{
			get
			{
				return this._Segment6;
			}
			set
			{
				if ((this._Segment6 != value))
				{
					this.OnSegment6Changing(value);
					this.SendPropertyChanging();
					this._Segment6 = value;
					this.SendPropertyChanged("Segment6");
					this.OnSegment6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment7", DbType="NVarChar(255)")]
		public string Segment7
		{
			get
			{
				return this._Segment7;
			}
			set
			{
				if ((this._Segment7 != value))
				{
					this.OnSegment7Changing(value);
					this.SendPropertyChanging();
					this._Segment7 = value;
					this.SendPropertyChanged("Segment7");
					this.OnSegment7Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Department")]
	public partial class TB_Department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Nullable<System.Guid> _ParentID;
		
		private string _Code;
		
		private string _Name;
		
		private string _Description;
		
		private string _Status;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _CreateOn;
		
		private string _UpdateBy;
		
		private System.Nullable<System.DateTime> _UpdateOn;
		
		private string _Segment1;
		
		private string _Segment2;
		
		private string _Segment3;
		
		private string _Segment4;
		
		private string _Segment5;
		
		private string _Segment6;
		
		private string _Segment7;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnParentIDChanging(System.Nullable<System.Guid> value);
    partial void OnParentIDChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnCreateOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateOnChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    partial void OnUpdateOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateOnChanged();
    partial void OnSegment1Changing(string value);
    partial void OnSegment1Changed();
    partial void OnSegment2Changing(string value);
    partial void OnSegment2Changed();
    partial void OnSegment3Changing(string value);
    partial void OnSegment3Changed();
    partial void OnSegment4Changing(string value);
    partial void OnSegment4Changed();
    partial void OnSegment5Changing(string value);
    partial void OnSegment5Changed();
    partial void OnSegment6Changing(string value);
    partial void OnSegment6Changed();
    partial void OnSegment7Changing(string value);
    partial void OnSegment7Changed();
    #endregion
		
		public TB_Department()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this.OnParentIDChanging(value);
					this.SendPropertyChanging();
					this._ParentID = value;
					this.SendPropertyChanged("ParentID");
					this.OnParentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(200)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(10)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateOn
		{
			get
			{
				return this._CreateOn;
			}
			set
			{
				if ((this._CreateOn != value))
				{
					this.OnCreateOnChanging(value);
					this.SendPropertyChanging();
					this._CreateOn = value;
					this.SendPropertyChanged("CreateOn");
					this.OnCreateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(50)")]
		public string UpdateBy
		{
			get
			{
				return this._UpdateBy;
			}
			set
			{
				if ((this._UpdateBy != value))
				{
					this.OnUpdateByChanging(value);
					this.SendPropertyChanging();
					this._UpdateBy = value;
					this.SendPropertyChanged("UpdateBy");
					this.OnUpdateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateOn
		{
			get
			{
				return this._UpdateOn;
			}
			set
			{
				if ((this._UpdateOn != value))
				{
					this.OnUpdateOnChanging(value);
					this.SendPropertyChanging();
					this._UpdateOn = value;
					this.SendPropertyChanged("UpdateOn");
					this.OnUpdateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment1", DbType="NVarChar(255)")]
		public string Segment1
		{
			get
			{
				return this._Segment1;
			}
			set
			{
				if ((this._Segment1 != value))
				{
					this.OnSegment1Changing(value);
					this.SendPropertyChanging();
					this._Segment1 = value;
					this.SendPropertyChanged("Segment1");
					this.OnSegment1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment2", DbType="NVarChar(255)")]
		public string Segment2
		{
			get
			{
				return this._Segment2;
			}
			set
			{
				if ((this._Segment2 != value))
				{
					this.OnSegment2Changing(value);
					this.SendPropertyChanging();
					this._Segment2 = value;
					this.SendPropertyChanged("Segment2");
					this.OnSegment2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment3", DbType="NVarChar(255)")]
		public string Segment3
		{
			get
			{
				return this._Segment3;
			}
			set
			{
				if ((this._Segment3 != value))
				{
					this.OnSegment3Changing(value);
					this.SendPropertyChanging();
					this._Segment3 = value;
					this.SendPropertyChanged("Segment3");
					this.OnSegment3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment4", DbType="NVarChar(255)")]
		public string Segment4
		{
			get
			{
				return this._Segment4;
			}
			set
			{
				if ((this._Segment4 != value))
				{
					this.OnSegment4Changing(value);
					this.SendPropertyChanging();
					this._Segment4 = value;
					this.SendPropertyChanged("Segment4");
					this.OnSegment4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment5", DbType="NVarChar(255)")]
		public string Segment5
		{
			get
			{
				return this._Segment5;
			}
			set
			{
				if ((this._Segment5 != value))
				{
					this.OnSegment5Changing(value);
					this.SendPropertyChanging();
					this._Segment5 = value;
					this.SendPropertyChanged("Segment5");
					this.OnSegment5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment6", DbType="NVarChar(255)")]
		public string Segment6
		{
			get
			{
				return this._Segment6;
			}
			set
			{
				if ((this._Segment6 != value))
				{
					this.OnSegment6Changing(value);
					this.SendPropertyChanging();
					this._Segment6 = value;
					this.SendPropertyChanged("Segment6");
					this.OnSegment6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment7", DbType="NVarChar(255)")]
		public string Segment7
		{
			get
			{
				return this._Segment7;
			}
			set
			{
				if ((this._Segment7 != value))
				{
					this.OnSegment7Changing(value);
					this.SendPropertyChanging();
					this._Segment7 = value;
					this.SendPropertyChanged("Segment7");
					this.OnSegment7Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Factory")]
	public partial class TB_Factory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _Code;
		
		private string _Name;
		
		private string _Description;
		
		private string _Status;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _CreateOn;
		
		private string _UpdateBy;
		
		private System.Nullable<System.DateTime> _UpdateOn;
		
		private string _Segment1;
		
		private string _Segment2;
		
		private string _Segment3;
		
		private string _Segment4;
		
		private string _Segment5;
		
		private string _Segment6;
		
		private string _Segment7;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnCreateOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateOnChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    partial void OnUpdateOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateOnChanged();
    partial void OnSegment1Changing(string value);
    partial void OnSegment1Changed();
    partial void OnSegment2Changing(string value);
    partial void OnSegment2Changed();
    partial void OnSegment3Changing(string value);
    partial void OnSegment3Changed();
    partial void OnSegment4Changing(string value);
    partial void OnSegment4Changed();
    partial void OnSegment5Changing(string value);
    partial void OnSegment5Changed();
    partial void OnSegment6Changing(string value);
    partial void OnSegment6Changed();
    partial void OnSegment7Changing(string value);
    partial void OnSegment7Changed();
    #endregion
		
		public TB_Factory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(200)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(10)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateOn
		{
			get
			{
				return this._CreateOn;
			}
			set
			{
				if ((this._CreateOn != value))
				{
					this.OnCreateOnChanging(value);
					this.SendPropertyChanging();
					this._CreateOn = value;
					this.SendPropertyChanged("CreateOn");
					this.OnCreateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(50)")]
		public string UpdateBy
		{
			get
			{
				return this._UpdateBy;
			}
			set
			{
				if ((this._UpdateBy != value))
				{
					this.OnUpdateByChanging(value);
					this.SendPropertyChanging();
					this._UpdateBy = value;
					this.SendPropertyChanged("UpdateBy");
					this.OnUpdateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateOn
		{
			get
			{
				return this._UpdateOn;
			}
			set
			{
				if ((this._UpdateOn != value))
				{
					this.OnUpdateOnChanging(value);
					this.SendPropertyChanging();
					this._UpdateOn = value;
					this.SendPropertyChanged("UpdateOn");
					this.OnUpdateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment1", DbType="NVarChar(255)")]
		public string Segment1
		{
			get
			{
				return this._Segment1;
			}
			set
			{
				if ((this._Segment1 != value))
				{
					this.OnSegment1Changing(value);
					this.SendPropertyChanging();
					this._Segment1 = value;
					this.SendPropertyChanged("Segment1");
					this.OnSegment1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment2", DbType="NVarChar(255)")]
		public string Segment2
		{
			get
			{
				return this._Segment2;
			}
			set
			{
				if ((this._Segment2 != value))
				{
					this.OnSegment2Changing(value);
					this.SendPropertyChanging();
					this._Segment2 = value;
					this.SendPropertyChanged("Segment2");
					this.OnSegment2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment3", DbType="NVarChar(255)")]
		public string Segment3
		{
			get
			{
				return this._Segment3;
			}
			set
			{
				if ((this._Segment3 != value))
				{
					this.OnSegment3Changing(value);
					this.SendPropertyChanging();
					this._Segment3 = value;
					this.SendPropertyChanged("Segment3");
					this.OnSegment3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment4", DbType="NVarChar(255)")]
		public string Segment4
		{
			get
			{
				return this._Segment4;
			}
			set
			{
				if ((this._Segment4 != value))
				{
					this.OnSegment4Changing(value);
					this.SendPropertyChanging();
					this._Segment4 = value;
					this.SendPropertyChanged("Segment4");
					this.OnSegment4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment5", DbType="NVarChar(255)")]
		public string Segment5
		{
			get
			{
				return this._Segment5;
			}
			set
			{
				if ((this._Segment5 != value))
				{
					this.OnSegment5Changing(value);
					this.SendPropertyChanging();
					this._Segment5 = value;
					this.SendPropertyChanged("Segment5");
					this.OnSegment5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment6", DbType="NVarChar(255)")]
		public string Segment6
		{
			get
			{
				return this._Segment6;
			}
			set
			{
				if ((this._Segment6 != value))
				{
					this.OnSegment6Changing(value);
					this.SendPropertyChanging();
					this._Segment6 = value;
					this.SendPropertyChanged("Segment6");
					this.OnSegment6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment7", DbType="NVarChar(255)")]
		public string Segment7
		{
			get
			{
				return this._Segment7;
			}
			set
			{
				if ((this._Segment7 != value))
				{
					this.OnSegment7Changing(value);
					this.SendPropertyChanging();
					this._Segment7 = value;
					this.SendPropertyChanged("Segment7");
					this.OnSegment7Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Menu")]
	public partial class TB_Menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Nullable<System.Guid> _ParentID;
		
		private string _Name;
		
		private string _Description;
		
		private string _CmdForm;
		
		private string _CmdExe;
		
		private string _Status;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _CreateOn;
		
		private string _UpdateBy;
		
		private System.Nullable<System.DateTime> _UpdateOn;
		
		private string _Segment1;
		
		private string _Segment2;
		
		private string _Segment3;
		
		private string _Segment4;
		
		private string _Segment5;
		
		private string _Segment6;
		
		private string _Segment7;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnParentIDChanging(System.Nullable<System.Guid> value);
    partial void OnParentIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnCmdFormChanging(string value);
    partial void OnCmdFormChanged();
    partial void OnCmdExeChanging(string value);
    partial void OnCmdExeChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnCreateOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateOnChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    partial void OnUpdateOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateOnChanged();
    partial void OnSegment1Changing(string value);
    partial void OnSegment1Changed();
    partial void OnSegment2Changing(string value);
    partial void OnSegment2Changed();
    partial void OnSegment3Changing(string value);
    partial void OnSegment3Changed();
    partial void OnSegment4Changing(string value);
    partial void OnSegment4Changed();
    partial void OnSegment5Changing(string value);
    partial void OnSegment5Changed();
    partial void OnSegment6Changing(string value);
    partial void OnSegment6Changed();
    partial void OnSegment7Changing(string value);
    partial void OnSegment7Changed();
    #endregion
		
		public TB_Menu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this.OnParentIDChanging(value);
					this.SendPropertyChanging();
					this._ParentID = value;
					this.SendPropertyChanged("ParentID");
					this.OnParentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(200)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CmdForm", DbType="NVarChar(100)")]
		public string CmdForm
		{
			get
			{
				return this._CmdForm;
			}
			set
			{
				if ((this._CmdForm != value))
				{
					this.OnCmdFormChanging(value);
					this.SendPropertyChanging();
					this._CmdForm = value;
					this.SendPropertyChanged("CmdForm");
					this.OnCmdFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CmdExe", DbType="NVarChar(100)")]
		public string CmdExe
		{
			get
			{
				return this._CmdExe;
			}
			set
			{
				if ((this._CmdExe != value))
				{
					this.OnCmdExeChanging(value);
					this.SendPropertyChanging();
					this._CmdExe = value;
					this.SendPropertyChanged("CmdExe");
					this.OnCmdExeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(10)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateOn
		{
			get
			{
				return this._CreateOn;
			}
			set
			{
				if ((this._CreateOn != value))
				{
					this.OnCreateOnChanging(value);
					this.SendPropertyChanging();
					this._CreateOn = value;
					this.SendPropertyChanged("CreateOn");
					this.OnCreateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(50)")]
		public string UpdateBy
		{
			get
			{
				return this._UpdateBy;
			}
			set
			{
				if ((this._UpdateBy != value))
				{
					this.OnUpdateByChanging(value);
					this.SendPropertyChanging();
					this._UpdateBy = value;
					this.SendPropertyChanged("UpdateBy");
					this.OnUpdateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateOn
		{
			get
			{
				return this._UpdateOn;
			}
			set
			{
				if ((this._UpdateOn != value))
				{
					this.OnUpdateOnChanging(value);
					this.SendPropertyChanging();
					this._UpdateOn = value;
					this.SendPropertyChanged("UpdateOn");
					this.OnUpdateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment1", DbType="NVarChar(255)")]
		public string Segment1
		{
			get
			{
				return this._Segment1;
			}
			set
			{
				if ((this._Segment1 != value))
				{
					this.OnSegment1Changing(value);
					this.SendPropertyChanging();
					this._Segment1 = value;
					this.SendPropertyChanged("Segment1");
					this.OnSegment1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment2", DbType="NVarChar(255)")]
		public string Segment2
		{
			get
			{
				return this._Segment2;
			}
			set
			{
				if ((this._Segment2 != value))
				{
					this.OnSegment2Changing(value);
					this.SendPropertyChanging();
					this._Segment2 = value;
					this.SendPropertyChanged("Segment2");
					this.OnSegment2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment3", DbType="NVarChar(255)")]
		public string Segment3
		{
			get
			{
				return this._Segment3;
			}
			set
			{
				if ((this._Segment3 != value))
				{
					this.OnSegment3Changing(value);
					this.SendPropertyChanging();
					this._Segment3 = value;
					this.SendPropertyChanged("Segment3");
					this.OnSegment3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment4", DbType="NVarChar(255)")]
		public string Segment4
		{
			get
			{
				return this._Segment4;
			}
			set
			{
				if ((this._Segment4 != value))
				{
					this.OnSegment4Changing(value);
					this.SendPropertyChanging();
					this._Segment4 = value;
					this.SendPropertyChanged("Segment4");
					this.OnSegment4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment5", DbType="NVarChar(255)")]
		public string Segment5
		{
			get
			{
				return this._Segment5;
			}
			set
			{
				if ((this._Segment5 != value))
				{
					this.OnSegment5Changing(value);
					this.SendPropertyChanging();
					this._Segment5 = value;
					this.SendPropertyChanged("Segment5");
					this.OnSegment5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment6", DbType="NVarChar(255)")]
		public string Segment6
		{
			get
			{
				return this._Segment6;
			}
			set
			{
				if ((this._Segment6 != value))
				{
					this.OnSegment6Changing(value);
					this.SendPropertyChanging();
					this._Segment6 = value;
					this.SendPropertyChanged("Segment6");
					this.OnSegment6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment7", DbType="NVarChar(255)")]
		public string Segment7
		{
			get
			{
				return this._Segment7;
			}
			set
			{
				if ((this._Segment7 != value))
				{
					this.OnSegment7Changing(value);
					this.SendPropertyChanging();
					this._Segment7 = value;
					this.SendPropertyChanged("Segment7");
					this.OnSegment7Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Role")]
	public partial class TB_Role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Nullable<System.Guid> _ParentID;
		
		private string _Code;
		
		private string _Name;
		
		private string _Description;
		
		private string _Status;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _CreateOn;
		
		private string _UpdateBy;
		
		private System.Nullable<System.DateTime> _UpdateOn;
		
		private string _Segment1;
		
		private string _Segment2;
		
		private string _Segment3;
		
		private string _Segment4;
		
		private string _Segment5;
		
		private string _Segment6;
		
		private string _Segment7;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnParentIDChanging(System.Nullable<System.Guid> value);
    partial void OnParentIDChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnCreateOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateOnChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    partial void OnUpdateOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateOnChanged();
    partial void OnSegment1Changing(string value);
    partial void OnSegment1Changed();
    partial void OnSegment2Changing(string value);
    partial void OnSegment2Changed();
    partial void OnSegment3Changing(string value);
    partial void OnSegment3Changed();
    partial void OnSegment4Changing(string value);
    partial void OnSegment4Changed();
    partial void OnSegment5Changing(string value);
    partial void OnSegment5Changed();
    partial void OnSegment6Changing(string value);
    partial void OnSegment6Changed();
    partial void OnSegment7Changing(string value);
    partial void OnSegment7Changed();
    #endregion
		
		public TB_Role()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this.OnParentIDChanging(value);
					this.SendPropertyChanging();
					this._ParentID = value;
					this.SendPropertyChanged("ParentID");
					this.OnParentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(200)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(10)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateOn
		{
			get
			{
				return this._CreateOn;
			}
			set
			{
				if ((this._CreateOn != value))
				{
					this.OnCreateOnChanging(value);
					this.SendPropertyChanging();
					this._CreateOn = value;
					this.SendPropertyChanged("CreateOn");
					this.OnCreateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(50)")]
		public string UpdateBy
		{
			get
			{
				return this._UpdateBy;
			}
			set
			{
				if ((this._UpdateBy != value))
				{
					this.OnUpdateByChanging(value);
					this.SendPropertyChanging();
					this._UpdateBy = value;
					this.SendPropertyChanged("UpdateBy");
					this.OnUpdateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateOn
		{
			get
			{
				return this._UpdateOn;
			}
			set
			{
				if ((this._UpdateOn != value))
				{
					this.OnUpdateOnChanging(value);
					this.SendPropertyChanging();
					this._UpdateOn = value;
					this.SendPropertyChanged("UpdateOn");
					this.OnUpdateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment1", DbType="NVarChar(255)")]
		public string Segment1
		{
			get
			{
				return this._Segment1;
			}
			set
			{
				if ((this._Segment1 != value))
				{
					this.OnSegment1Changing(value);
					this.SendPropertyChanging();
					this._Segment1 = value;
					this.SendPropertyChanged("Segment1");
					this.OnSegment1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment2", DbType="NVarChar(255)")]
		public string Segment2
		{
			get
			{
				return this._Segment2;
			}
			set
			{
				if ((this._Segment2 != value))
				{
					this.OnSegment2Changing(value);
					this.SendPropertyChanging();
					this._Segment2 = value;
					this.SendPropertyChanged("Segment2");
					this.OnSegment2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment3", DbType="NVarChar(255)")]
		public string Segment3
		{
			get
			{
				return this._Segment3;
			}
			set
			{
				if ((this._Segment3 != value))
				{
					this.OnSegment3Changing(value);
					this.SendPropertyChanging();
					this._Segment3 = value;
					this.SendPropertyChanged("Segment3");
					this.OnSegment3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment4", DbType="NVarChar(255)")]
		public string Segment4
		{
			get
			{
				return this._Segment4;
			}
			set
			{
				if ((this._Segment4 != value))
				{
					this.OnSegment4Changing(value);
					this.SendPropertyChanging();
					this._Segment4 = value;
					this.SendPropertyChanged("Segment4");
					this.OnSegment4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment5", DbType="NVarChar(255)")]
		public string Segment5
		{
			get
			{
				return this._Segment5;
			}
			set
			{
				if ((this._Segment5 != value))
				{
					this.OnSegment5Changing(value);
					this.SendPropertyChanging();
					this._Segment5 = value;
					this.SendPropertyChanged("Segment5");
					this.OnSegment5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment6", DbType="NVarChar(255)")]
		public string Segment6
		{
			get
			{
				return this._Segment6;
			}
			set
			{
				if ((this._Segment6 != value))
				{
					this.OnSegment6Changing(value);
					this.SendPropertyChanging();
					this._Segment6 = value;
					this.SendPropertyChanged("Segment6");
					this.OnSegment6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment7", DbType="NVarChar(255)")]
		public string Segment7
		{
			get
			{
				return this._Segment7;
			}
			set
			{
				if ((this._Segment7 != value))
				{
					this.OnSegment7Changing(value);
					this.SendPropertyChanging();
					this._Segment7 = value;
					this.SendPropertyChanged("Segment7");
					this.OnSegment7Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Role_R")]
	public partial class TB_Role_R : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Guid _RoleID;
		
		private System.Guid _RID;
		
		private string _RName;
		
		private string _Status;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _CreateOn;
		
		private string _UpdateBy;
		
		private System.Nullable<System.DateTime> _UpdateOn;
		
		private string _Segment1;
		
		private string _Segment2;
		
		private string _Segment3;
		
		private string _Segment4;
		
		private string _Segment5;
		
		private string _Segment6;
		
		private string _Segment7;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnRoleIDChanging(System.Guid value);
    partial void OnRoleIDChanged();
    partial void OnRIDChanging(System.Guid value);
    partial void OnRIDChanged();
    partial void OnRNameChanging(string value);
    partial void OnRNameChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnCreateOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateOnChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    partial void OnUpdateOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateOnChanged();
    partial void OnSegment1Changing(string value);
    partial void OnSegment1Changed();
    partial void OnSegment2Changing(string value);
    partial void OnSegment2Changed();
    partial void OnSegment3Changing(string value);
    partial void OnSegment3Changed();
    partial void OnSegment4Changing(string value);
    partial void OnSegment4Changed();
    partial void OnSegment5Changing(string value);
    partial void OnSegment5Changed();
    partial void OnSegment6Changing(string value);
    partial void OnSegment6Changed();
    partial void OnSegment7Changing(string value);
    partial void OnSegment7Changed();
    #endregion
		
		public TB_Role_R()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid RID
		{
			get
			{
				return this._RID;
			}
			set
			{
				if ((this._RID != value))
				{
					this.OnRIDChanging(value);
					this.SendPropertyChanging();
					this._RID = value;
					this.SendPropertyChanged("RID");
					this.OnRIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RName", DbType="NVarChar(50)")]
		public string RName
		{
			get
			{
				return this._RName;
			}
			set
			{
				if ((this._RName != value))
				{
					this.OnRNameChanging(value);
					this.SendPropertyChanging();
					this._RName = value;
					this.SendPropertyChanged("RName");
					this.OnRNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(10)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateOn
		{
			get
			{
				return this._CreateOn;
			}
			set
			{
				if ((this._CreateOn != value))
				{
					this.OnCreateOnChanging(value);
					this.SendPropertyChanging();
					this._CreateOn = value;
					this.SendPropertyChanged("CreateOn");
					this.OnCreateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(50)")]
		public string UpdateBy
		{
			get
			{
				return this._UpdateBy;
			}
			set
			{
				if ((this._UpdateBy != value))
				{
					this.OnUpdateByChanging(value);
					this.SendPropertyChanging();
					this._UpdateBy = value;
					this.SendPropertyChanged("UpdateBy");
					this.OnUpdateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateOn
		{
			get
			{
				return this._UpdateOn;
			}
			set
			{
				if ((this._UpdateOn != value))
				{
					this.OnUpdateOnChanging(value);
					this.SendPropertyChanging();
					this._UpdateOn = value;
					this.SendPropertyChanged("UpdateOn");
					this.OnUpdateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment1", DbType="NVarChar(255)")]
		public string Segment1
		{
			get
			{
				return this._Segment1;
			}
			set
			{
				if ((this._Segment1 != value))
				{
					this.OnSegment1Changing(value);
					this.SendPropertyChanging();
					this._Segment1 = value;
					this.SendPropertyChanged("Segment1");
					this.OnSegment1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment2", DbType="NVarChar(255)")]
		public string Segment2
		{
			get
			{
				return this._Segment2;
			}
			set
			{
				if ((this._Segment2 != value))
				{
					this.OnSegment2Changing(value);
					this.SendPropertyChanging();
					this._Segment2 = value;
					this.SendPropertyChanged("Segment2");
					this.OnSegment2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment3", DbType="NVarChar(255)")]
		public string Segment3
		{
			get
			{
				return this._Segment3;
			}
			set
			{
				if ((this._Segment3 != value))
				{
					this.OnSegment3Changing(value);
					this.SendPropertyChanging();
					this._Segment3 = value;
					this.SendPropertyChanged("Segment3");
					this.OnSegment3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment4", DbType="NVarChar(255)")]
		public string Segment4
		{
			get
			{
				return this._Segment4;
			}
			set
			{
				if ((this._Segment4 != value))
				{
					this.OnSegment4Changing(value);
					this.SendPropertyChanging();
					this._Segment4 = value;
					this.SendPropertyChanged("Segment4");
					this.OnSegment4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment5", DbType="NVarChar(255)")]
		public string Segment5
		{
			get
			{
				return this._Segment5;
			}
			set
			{
				if ((this._Segment5 != value))
				{
					this.OnSegment5Changing(value);
					this.SendPropertyChanging();
					this._Segment5 = value;
					this.SendPropertyChanged("Segment5");
					this.OnSegment5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment6", DbType="NVarChar(255)")]
		public string Segment6
		{
			get
			{
				return this._Segment6;
			}
			set
			{
				if ((this._Segment6 != value))
				{
					this.OnSegment6Changing(value);
					this.SendPropertyChanging();
					this._Segment6 = value;
					this.SendPropertyChanged("Segment6");
					this.OnSegment6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment7", DbType="NVarChar(255)")]
		public string Segment7
		{
			get
			{
				return this._Segment7;
			}
			set
			{
				if ((this._Segment7 != value))
				{
					this.OnSegment7Changing(value);
					this.SendPropertyChanging();
					this._Segment7 = value;
					this.SendPropertyChanged("Segment7");
					this.OnSegment7Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Udc")]
	public partial class TB_Udc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _SysCode;
		
		private string _Category;
		
		private string _Code;
		
		private string _Value;
		
		private string _Description;
		
		private string _Status;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _CreateOn;
		
		private string _UpdateBy;
		
		private System.Nullable<System.DateTime> _UpdateOn;
		
		private string _Segment1;
		
		private string _Segment2;
		
		private string _Segment3;
		
		private string _Segment4;
		
		private string _Segment5;
		
		private string _Segment6;
		
		private string _Segment7;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnSysCodeChanging(string value);
    partial void OnSysCodeChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnValueChanging(string value);
    partial void OnValueChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnCreateOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateOnChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    partial void OnUpdateOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateOnChanged();
    partial void OnSegment1Changing(string value);
    partial void OnSegment1Changed();
    partial void OnSegment2Changing(string value);
    partial void OnSegment2Changed();
    partial void OnSegment3Changing(string value);
    partial void OnSegment3Changed();
    partial void OnSegment4Changing(string value);
    partial void OnSegment4Changed();
    partial void OnSegment5Changing(string value);
    partial void OnSegment5Changed();
    partial void OnSegment6Changing(string value);
    partial void OnSegment6Changed();
    partial void OnSegment7Changing(string value);
    partial void OnSegment7Changed();
    #endregion
		
		public TB_Udc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SysCode
		{
			get
			{
				return this._SysCode;
			}
			set
			{
				if ((this._SysCode != value))
				{
					this.OnSysCodeChanging(value);
					this.SendPropertyChanging();
					this._SysCode = value;
					this.SendPropertyChanged("SysCode");
					this.OnSysCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="NVarChar(100)")]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(200)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(10)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateOn
		{
			get
			{
				return this._CreateOn;
			}
			set
			{
				if ((this._CreateOn != value))
				{
					this.OnCreateOnChanging(value);
					this.SendPropertyChanging();
					this._CreateOn = value;
					this.SendPropertyChanged("CreateOn");
					this.OnCreateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(50)")]
		public string UpdateBy
		{
			get
			{
				return this._UpdateBy;
			}
			set
			{
				if ((this._UpdateBy != value))
				{
					this.OnUpdateByChanging(value);
					this.SendPropertyChanging();
					this._UpdateBy = value;
					this.SendPropertyChanged("UpdateBy");
					this.OnUpdateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateOn
		{
			get
			{
				return this._UpdateOn;
			}
			set
			{
				if ((this._UpdateOn != value))
				{
					this.OnUpdateOnChanging(value);
					this.SendPropertyChanging();
					this._UpdateOn = value;
					this.SendPropertyChanged("UpdateOn");
					this.OnUpdateOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment1", DbType="NVarChar(255)")]
		public string Segment1
		{
			get
			{
				return this._Segment1;
			}
			set
			{
				if ((this._Segment1 != value))
				{
					this.OnSegment1Changing(value);
					this.SendPropertyChanging();
					this._Segment1 = value;
					this.SendPropertyChanged("Segment1");
					this.OnSegment1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment2", DbType="NVarChar(255)")]
		public string Segment2
		{
			get
			{
				return this._Segment2;
			}
			set
			{
				if ((this._Segment2 != value))
				{
					this.OnSegment2Changing(value);
					this.SendPropertyChanging();
					this._Segment2 = value;
					this.SendPropertyChanged("Segment2");
					this.OnSegment2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment3", DbType="NVarChar(255)")]
		public string Segment3
		{
			get
			{
				return this._Segment3;
			}
			set
			{
				if ((this._Segment3 != value))
				{
					this.OnSegment3Changing(value);
					this.SendPropertyChanging();
					this._Segment3 = value;
					this.SendPropertyChanged("Segment3");
					this.OnSegment3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment4", DbType="NVarChar(255)")]
		public string Segment4
		{
			get
			{
				return this._Segment4;
			}
			set
			{
				if ((this._Segment4 != value))
				{
					this.OnSegment4Changing(value);
					this.SendPropertyChanging();
					this._Segment4 = value;
					this.SendPropertyChanged("Segment4");
					this.OnSegment4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment5", DbType="NVarChar(255)")]
		public string Segment5
		{
			get
			{
				return this._Segment5;
			}
			set
			{
				if ((this._Segment5 != value))
				{
					this.OnSegment5Changing(value);
					this.SendPropertyChanging();
					this._Segment5 = value;
					this.SendPropertyChanged("Segment5");
					this.OnSegment5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment6", DbType="NVarChar(255)")]
		public string Segment6
		{
			get
			{
				return this._Segment6;
			}
			set
			{
				if ((this._Segment6 != value))
				{
					this.OnSegment6Changing(value);
					this.SendPropertyChanging();
					this._Segment6 = value;
					this.SendPropertyChanged("Segment6");
					this.OnSegment6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment7", DbType="NVarChar(255)")]
		public string Segment7
		{
			get
			{
				return this._Segment7;
			}
			set
			{
				if ((this._Segment7 != value))
				{
					this.OnSegment7Changing(value);
					this.SendPropertyChanging();
					this._Segment7 = value;
					this.SendPropertyChanged("Segment7");
					this.OnSegment7Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
